/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check endpoint
         * @description Verifies application runtime and active PostgreSQL database connectivity via Prisma 7.
         */
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out user by revoking current JWT token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve currently authenticated user profile */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects belonging to the authenticated user */
        get: operations["ProjectsController_findAll"];
        put?: never;
        /** Create a new project for the authenticated user */
        post: operations["ProjectsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a project by ID (must be owned by user) */
        get: operations["ProjectsController_findOne"];
        /** Update an existing project owned by user */
        put: operations["ProjectsController_update"];
        post?: never;
        /** Delete a project owned by user */
        delete: operations["ProjectsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tasks for a project owned by user */
        get: operations["ProjectsController_findTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tasks owned by the authenticated user */
        get: operations["TasksController_findAll"];
        put?: never;
        /** Create a new task in a project owned by user */
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get task by ID (must belong to project owned by user) */
        get: operations["TasksController_findOne"];
        /** Update an existing task owned by user */
        put: operations["TasksController_update"];
        post?: never;
        /** Delete a task owned by user */
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get summary metrics for authenticated user */
        get: operations["DashboardController_getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description Full name of the user
             * @example Demo User
             */
            fullName: string;
            /**
             * @description Email address of the user
             * @example demo@example.com
             */
            email: string;
            /**
             * @description User password (minimum 8 characters)
             * @example SecurePassword123!
             */
            password: string;
        };
        LoginDto: {
            /**
             * @description Email address of the user
             * @example demo@example.com
             */
            email: string;
            /**
             * @description User password
             * @example SecurePassword123!
             */
            password: string;
        };
        CreateProjectDto: {
            /**
             * @description Project name
             * @example Mobile App Redesign
             */
            name: string;
            /**
             * @description Project description
             * @example Redesign UI components
             */
            description?: string;
            /**
             * @description Project status
             * @default NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /**
             * @description Start date in ISO format (YYYY-MM-DD)
             * @example 2026-10-01
             */
            startDate?: string;
            /**
             * @description End date in ISO format (YYYY-MM-DD)
             * @example 2026-12-31
             */
            endDate?: string;
        };
        UpdateProjectDto: {
            /**
             * @description Project name
             * @example Mobile App Redesign Updated
             */
            name?: string;
            /**
             * @description Project description
             * @example Updated description
             */
            description?: string;
            /**
             * @description Project status
             * @enum {string}
             */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            /**
             * @description Start date in ISO format (YYYY-MM-DD)
             * @example 2026-10-01
             */
            startDate?: string;
            /**
             * @description End date in ISO format (YYYY-MM-DD)
             * @example 2026-12-31
             */
            endDate?: string;
        };
        CreateTaskDto: {
            /**
             * @description Parent Project UUID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            projectId: string;
            /**
             * @description Task name
             * @example Implement auth guard
             */
            name: string;
            /**
             * @description Task description
             * @example Extract JWT and verify claims
             */
            description?: string;
            /**
             * @description Task priority
             * @default MEDIUM
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH";
            /**
             * @description Task status
             * @default PENDING
             * @enum {string}
             */
            status: "PENDING" | "IN_PROGRESS" | "COMPLETED";
            /**
             * @description Due date in ISO format (YYYY-MM-DD)
             * @example 2026-11-01
             */
            dueDate?: string;
        };
        UpdateTaskDto: {
            /**
             * @description Task name
             * @example Updated task name
             */
            name?: string;
            /**
             * @description Task description
             * @example Updated description
             */
            description?: string;
            /**
             * @description Task priority
             * @enum {string}
             */
            priority?: "LOW" | "MEDIUM" | "HIGH";
            /**
             * @description Task status
             * @enum {string}
             */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED";
            /**
             * @description Due date in ISO format (YYYY-MM-DD)
             * @example 2026-11-01
             */
            dueDate?: string;
        };
        DashboardResponseDto: {
            /**
             * @description Total number of projects owned by user
             * @example 5
             */
            totalProjects: number;
            /**
             * @description Total number of tasks across owned projects
             * @example 12
             */
            totalTasks: number;
            /**
             * @description Total number of completed tasks
             * @example 7
             */
            completedTasks: number;
            /**
             * @description Total number of pending tasks
             * @example 4
             */
            pendingTasks: number;
            /**
             * @description Total number of projects currently in progress
             * @example 2
             */
            projectsInProgress: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application and database are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Database connectivity failure */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully with access token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed or missing fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Successfully authenticated, returns access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded (5 requests per minute) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token successfully revoked and invalidated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, invalid, or already revoked access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user profile returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized (token missing, invalid, or revoked) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findAll: {
        parameters: {
            query?: {
                /** @description Search term matching project name */
                search?: string;
                /** @description Filter by project status */
                status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of owned projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectDto"];
            };
        };
        responses: {
            /** @description Project successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed or invalid dates */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectDto"];
            };
        };
        responses: {
            /** @description Project updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed or invalid dates */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProjectsController_findTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tasks in project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findAll: {
        parameters: {
            query?: {
                /** @description Search term matching task name */
                search?: string;
                /** @description Filter by task status */
                status?: "PENDING" | "IN_PROGRESS" | "COMPLETED";
                /** @description Filter by task priority */
                priority?: "LOW" | "MEDIUM" | "HIGH";
                /** @description Filter by project ID */
                projectId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of owned tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            /** @description Task successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            /** @description Task successfully updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task successfully deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found or not owned by user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DashboardController_getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dashboard metrics calculated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
        };
    };
}
